name: 'Superblocks Import'
description: 'Push Applications, Workflows, and Scheduled Jobs to Superblocks'
inputs:
  token:
    description: 'The Superblocks access token to use'
    required: true
  domain:
    description: 'The Superblocks domain where resources are hosted'
    default: 'app.superblocks.com'
  path:
    description: 'The relative path from repo root to the Superblocks root directory. This is where the ~.superblocks/superblocks.json config file is located.'
    default: '.'
  sha:
    description: 'Commit to push changes for'
    default: 'HEAD'
  signing_agent_profile:
    description: 'The Superblocks profile to use for selecting the signing agent'
    default: ''

runs:
  using: 'docker'
  image: 'docker://superblocksteam/import-action:v1'
  env:
    SUPERBLOCKS_TOKEN: ${{ inputs.token }}
    SUPERBLOCKS_DOMAIN: ${{ inputs.domain }}
    SUPERBLOCKS_PATH: ${{ inputs.path }}
    COMMIT_SHA: ${{ inputs.sha }}
    SUPERBLOCKS_PROFILE: ${{ inputs.signing_agent_profile }}
