name: 'Superblocks Import'
description: 'Push applications to Superblocks'
inputs:
  sha:
    description: 'Commit to push changes for'
    default: 'HEAD'
  token:
    description: 'The Superblocks access token to use'
    required: true
  domain:
    description: 'The Superblocks domain where applications are hosted'
    default: 'app.superblocks.com'
  path:
    description: 'The relative path to the Superblocks config file'
    default: '.superblocks/superblocks.json'
  cli-version:
    description: 'The Superblocks CLI version'
    # TODO(taha) Change this to a better default once the CLI + action is made public
    default: branch-awareness
  # TODO(taha) Remove the following once the CLI + action is made public
  github-token:
    description: 'The GitHub package registry access token to use when installing the Superblocks CLI'
    required: true

outputs:
  imported: # id of output
    description: 'import status'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.sha }}
    - ${{ inputs.token }}
    - ${{ inputs.domain }}
    - ${{ inputs.path }}
    - ${{ inputs.cli-version }}
    - ${{ inputs.github-token }}
