name: 'Superblocks Import'
description: 'Push applications to Superblocks'
inputs:
  sha:
    description: 'Commit to push changes for'
    default: 'HEAD'
  token:
    description: 'The Superblocks access token to use'
    required: true
  domain:
    description: 'The Superblocks domain where applications are hosted'
    default: 'app.superblocks.com'
  path:
    description: 'The relative path to the Superblocks config file'
    default: '.superblocks/superblocks.json'

runs:
  using: 'docker'
  image: 'superblocksteam/import-action:v1.0.2'
  args:
    - ${{ inputs.sha }}
    - ${{ inputs.token }}
    - ${{ inputs.domain }}
    - ${{ inputs.path }}
  env:
    SUPERBLOCKS_AUTHOR_NAME: 'superblocks-app[bot]'
    SUPERBLOCKS_COMMIT_MESSAGE_IDENTIFIER: '[superblocks ci]'
